language: generic

os: 
  - linux

dist: xenial

services:
  - docker

before_install:
  - docker build -t saphirdev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true saphirdev/docker-react npm run test
